FILE1 = images/pessoa.jpeg
FILE2 = images/pessoa.jpeg
FILE3 = images/pessoa.jpeg

time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg
time -o main_1.txt  -a -f "%e" ./main images/pessoa.jpeg
time -o main1_1.txt -a -f "%e" ./main1 images/pessoa.jpeg
time -o main2_1.txt -a -f "%e" ./main2 images/pessoa.jpeg 
time -o main_2.txt  -a -f "%e" ./main  images/cachorro.jpg
time -o main1_2.txt -a -f "%e" ./main1 images/cachorro.jpg
time -o main2_2.txt -a -f "%e" ./main2 images/cachorro.jpg
time -o main_3.txt  -a -f "%e" ./main  images/image.jpg 
time -o main1_3.txt -a -f "%e" ./main1 images/image.jpg
time -o main2_3.txt -a -f "%e" ./main2 images/image.jpg

