FILE1 = images/cachorro.jpg
FILE2 = images/cachorro.jpg
FILE3 = images/cachorro.jpg

time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3
time -o main_1.txt  -a -f "%e" ./main $FILE1
time -o main1_1.txt -a -f "%e" ./main1 $FILE1
time -o main2_1.txt -a -f "%e" ./main2 $FILE1 
time -o main_2.txt  -a -f "%e" ./main  $FILE2
time -o main1_2.txt -a -f "%e" ./main1 $FILE2
time -o main2_2.txt -a -f "%e" ./main2 $FILE2
time -o main_3.txt  -a -f "%e" ./main  $FILE3 
time -o main1_3.txt -a -f "%e" ./main1 $FILE3
time -o main2_3.txt -a -f "%e" ./main2 $FILE3

